// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://klodyvpfcbqayqmdikvh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtsb2R5dnBmY2JxYXlxbWRpa3ZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3NDg0NjksImV4cCI6MjA3MjMyNDQ2OX0.wl9LG9qKk1Ce_FvOtyDnlkcGhUeJdLPWV29ol806pmg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});